config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/welcome'
  resources :telephones
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    get "home/index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/telephone.rb
class Telephone < ApplicationRecord
    
    
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def welcome
  end
end

app/controllers/home/index_controller.rb
class Home::IndexController < ApplicationController
end

app/controllers/telephones_controller.rb
class TelephonesController < ApplicationController
  before_action :set_telephone, only: %i[ show edit update destroy ]

  # GET /telephones or /telephones.json
  def index
    @telephones = Telephone.all
  end

  # GET /telephones/1 or /telephones/1.json
  def show
  end

  # GET /telephones/new
  def new
    @telephone = Telephone.new
  end

  # GET /telephones/1/edit
  def edit
  end

  # POST /telephones or /telephones.json
  def create
    @telephone = Telephone.new(telephone_params)

    respond_to do |format|
      if @telephone.save
        format.html { redirect_to telephone_url(@telephone), notice: "Telephone was successfully created." }
        format.json { render :show, status: :created, location: @telephone }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @telephone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /telephones/1 or /telephones/1.json
  def update
    respond_to do |format|
      if @telephone.update(telephone_params)
        format.html { redirect_to telephone_url(@telephone), notice: "Telephone was successfully updated." }
        format.json { render :show, status: :ok, location: @telephone }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @telephone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /telephones/1 or /telephones/1.json
  def destroy
    @telephone.destroy

    respond_to do |format|
      format.html { redirect_to telephones_url, notice: "Telephone was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_telephone
      @telephone = Telephone.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def telephone_params
      params.require(:telephone).permit(:firstname, :phono, :address, :lastname, :emailid, :doorno, :street, :area, :city, :state, :country)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home/index_helper.rb
module Home::IndexHelper
end

app/helpers/telephones_helper.rb
module TelephonesHelper
end

app/views/dashboard/welcome.html.erb
<%= form_with(url: "/search", method: "get") do %>
    <%= label_tag(:q, "Search for:") %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Search") %>
    <%= check_box_tag(:pet_dog) %>
<%= label_tag(:pet_dog, "I own a dog") %>
<%= check_box_tag(:pet_cat) %>
<%= label_tag(:pet_cat, "I own a cat") %>
<input id="pet_dog" name="pet_dog" type="checkbox" value="1" />
<label for="pet_dog">I own a dog</label>
<input id="pet_cat" name="pet_cat" type="checkbox" value="1" />
<label for="pet_cat">I own a cat</label>

<%= radio_button_tag(:age, "child") %>
<%= label_tag(:age_child, "I am younger than 21") %>
<%= radio_button_tag(:age, "adult") %>
<%= label_tag(:age_adult, "I am over 21") %>

<%= text_area_tag(:message, "Hi, nice site", size: "24x6") %>
<%= password_field_tag(:password) %>
<%= hidden_field_tag(:parent_id, "5") %>
<%= search_field(:user, :name) %>
<%= telephone_field(:user, :phone) %>
<%= date_field(:user, :born_on) %>
<%= datetime_local_field(:user, :graduation_day) %>
<%= month_field(:user, :birthday_month) %>
<%= week_field(:user, :birthday_week) %>
<%= url_field(:user, :homepage) %>
<%= email_field(:user, :address) %>
<%= color_field(:user, :favorite_color) %>
<%= time_field(:task, :started_at) %>
<%= number_field(:product, :price, in: 1.0..20.0, step: 0.5) %>
<%= range_field(:product, :discount, in: 1..100) %>

  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<div class="content">
		<div id="top">
			<div class="topright">
			 	<a href="#"><img src="assets/sitemap.png" alt="" /></a> 
			 	<a href="#"><img src="assets/rss.png" alt="" /></a>				
			</div>
		</div>
    <%= yield %>
    
		<div id="header">
			
			<div class="headings">
				<h1>Telephone app</h1>
				<h2>rails exercises</h2>
			</div>
		</div>
    
	
			<div id="menu">
			  	<ul>
					<li><a href="#">first name</a></li>
					<li><a href="#">phoneno</a></li>
					<li><a href="#">address</a></li>
					<li><a href="#">lastname</a></li>
      				<li><a href="#">email id</a></li>
      				<li><a href="#">door no</a></li>
              <li><a href="#">street</a></li>
              <li><a href="#">area</a></li>
              <li><a href="#">city</a></li>
              <li><a href="#">state</a></li>
              <li><a href="#">country</a></li>
      			</ul>
			</div>	
			
     
		<div id="main">
			<div class="right">
				
				
				<div class="nav">
				
					
				</div>
			</div>
			
			
		</div>
		
		<div id="footer">
			<div class="info">
				&copy; 2023
        Telephone designn app <br />
				
		</div>
	</div>
	
  
  </body>
</html>

app/views/telephones/_form.html.erb
<%= form_with(model: telephone) do |form| %>
  <% if telephone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(telephone.errors.count, "error") %> prohibited this telephone from being saved:</h2>

      <ul>
        <% telephone.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>

  <div class="field">
    <%= form.label :phono %>
    <%= form.number_field :phono %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :emailid %>
    <%= form.text_field :emailid %>
  </div>

  <div class="field">
    <%= form.label :doorno %>
    <%= form.number_field :doorno %>
  </div>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_area :street %>
  </div>

  <div class="field">
    <%= form.label :area %>
    <%= form.text_area :area %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/telephones/edit.html.erb
<h1>Editing Telephone</h1>

<%= render 'form', telephone: @telephone %>

<%= link_to 'Show', @telephone %> |
<%= link_to 'Back', telephones_path %>

app/views/telephones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Telephones</h1>

<table>
  <thead>
    <tr>
      <th>first name</th>
      <th>Phone no</th>
      <th>Address</th>
      <th>Lastname</th>
      <th>Email id</th>
      <th>Door no</th>
      <th>Street</th>
      <th>Area</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @telephones.each do |telephone| %>
      <tr>
        <td><%= telephone.first name %></td>
        <td><%= telephone.phoneno %></td>
        <td><%= telephone.address %></td>
        <td><%= telephone.lastname %></td>
        <td><%= telephone.email id %></td>
        <td><%= telephone.doorno %></td>
        <td><%= telephone.street %></td>
        <td><%= telephone.area %></td>
        <td><%= telephone.city %></td>
        <td><%= telephone.state %></td>
        <td><%= telephone.country %></td>
        <td><%= link_to 'Show', telephone %></td>
        <td><%= link_to 'Edit', edit_telephone_path(telephone) %></td>
        <td><%= link_to 'Destroy', telephone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Telephone', new_telephone_path %>

app/views/telephones/new.html.erb
<h1>New Telephone</h1>

<%= render 'form', telephone: @telephone %>

<%= link_to 'Back', telephones_path %>

app/views/telephones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @telephone.firstname %>
</p>

<p>
  <strong>Phono:</strong>
  <%= @telephone.phono %>
</p>

<p>
  <strong>Address:</strong>
  <%= @telephone.address %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @telephone.lastname %>
</p>

<p>
  <strong>Emailid:</strong>
  <%= @telephone.emailid %>
</p>

<p>
  <strong>Doorno:</strong>
  <%= @telephone.doorno %>
</p>

<p>
  <strong>Street:</strong>
  <%= @telephone.street %>
</p>

<p>
  <strong>Area:</strong>
  <%= @telephone.area %>
</p>

<p>
  <strong>City:</strong>
  <%= @telephone.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @telephone.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @telephone.country %>
</p>

<%= link_to 'Edit', edit_telephone_path(@telephone) %> |
<%= link_to 'Back', telephones_path %>